"""Harness-generated turns must not be mistaken for things the user said."""

import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

from agent_recap.sources.claude_code import _is_synthetic

SYNTHETIC = [
    "<task-notification>\n<task-id>abc</task-id>\n</task-notification>",
    "<system-reminder>watch out</system-reminder>",
    "<local-command-stdout>ok</local-command-stdout>",
    "<command-name>/model</command-name>",
    "Caveat: The messages below were generated by the user while running local commands.",
    "what about the tests? <task-notification>x</task-notification>",
    "[Request interrupted by user]",
]

REAL = [
    "please add a filter by provider",
    "fix the bug in index.ts",
    "great start. whats next?",
    "can you check whether <div> tags break the parser?",
]


def test_synthetic_turns_are_detected():
    for text in SYNTHETIC:
        assert _is_synthetic(text), f"missed: {text[:50]}"


def test_real_messages_are_kept():
    for text in REAL:
        assert not _is_synthetic(text), f"wrongly dropped: {text[:50]}"
